# Generated by Django 4.1.6 on 2023-02-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateField(blank=True),
        ),
    ]
